export const drivers = [
    { id: 1, name: "Charles Leclerc", team: "Ferrari" },
    { id: 2, name: "Lewis Hamilton", team: "Mercedes" },
    { id: 3, name: "Max Verstappen", team: "Red Bull" },
    { id: 4, name: "Lando Norris", team: "McLaren" },
    { id: 5, name: "Esteban Ocon", team: "Alpine" },
    { id: 6, name: "Valtteri Bottas", team: "Alfa Romeo" },
    { id: 7, name: "Lance Stroll", team: "Aston Martin" },
    { id: 8, name: "Kevin Magnussen", team: "Haas" },
    { id: 9, name: "Nicholas Latifi", team: "Williams" },
    { id: 10, name: "Sebastian Vettel", team: "Aston Martin" },
    { id: 11, name: "Daniel Ricciardo", team: "McLaren" },
    { id: 12, name: "Carlos Sainz", team: "Ferrari" },
    { id: 13, name: "George Russell", team: "Mercedes" },
    { id: 14, name: "Sergio Perez", team: "Red Bull" },
]