export const teams = [
  { id: 1, name: "Ferrari", local: "Italy" },
  { id: 2, name: "Mercedes", local: "Germany" },
  { id: 3, name: "Red Bull", local: "Austria" },
  { id: 4, name: "McLaren", local: "United Kingdom" },
  { id: 5, name: "Alpine", local: "France" },
  { id: 6, name: "Alfa Romeo", local: "Switzerland" },
  { id: 7, name: "Aston Martin", local: "United Kingdom" },
  { id: 8, name: "Haas", local: "United States" },
  { id: 9, name: "Williams", local: "United Kingdom" },
  { id: 10, name: "Porsche", local: "Germany" },
  { id: 11, name: "Audi", local: "Germany" },
  { id: 12, name: "Sauber", local: "Switzerland" },
  { id: 13, name: "Toro Rosso", local: "Italy" },
  { id: 14, name: "Renault", local: "France" },
]